name: Publish Stable

on:
  push:
    branches:
      - dev-*
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - dev
      - main

env:
  version: 0.0.42a10

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            npm_config_arch: x64
          # - os: windows-latest
          #   platform: win32
          #   arch: ia32
          #   npm_config_arch: ia32
          - os: windows-latest
            platform: win32
            arch: arm64
            npm_config_arch: arm
          - os: ubuntu-latest
            platform: linux
            arch: x64
            npm_config_arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            npm_config_arch: arm64
          # - os: ubuntu-latest
          #   platform: linux
          #   arch: armhf
          #   npm_config_arch: arm
          # - os: ubuntu-latest
          #   platform: alpine
          #   arch: x64
          #   npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
            npm_config_arch: arm64
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
      # - run: npm install --legacy-peer-deps
      - run: npm install 
      - shell: pwsh
        run: |
          echo "target=${{ matrix.platform }}-${{ matrix.arch }}" >> $env:GITHUB_ENV
          npm run package
          node dist/prefetch.js ${{ matrix.platform }} ${{ matrix.arch }}
      - run: npx vsce package --target ${{ env.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: dothttp-runner-${{ env.target }}
          path: "*.vsix"
  non-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           node-version: 20.x
      - run: npm install 
      - shell: pwsh
        run: npm run package
      - run: npx vsce package
      - uses: actions/upload-artifact@v4
        with:
          name: without-cli
          path: "*.vsix"
  publish-vscode-market-place:
    runs-on: ubuntu-latest
    needs: [build, non-cli]
    if: success() && startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
      - uses: actions/download-artifact@v4
      - run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.MARKETPLACE_PAT }}
        continue-on-error: true

  publish-ovsx:
    runs-on: ubuntu-latest
    needs: [build, non-cli]
    if: success() && startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
      - uses: actions/download-artifact@v4
      - run: npx ovsx publish --packagePath $(find . -iname *.vsix)
        env:
          OVSX_PAT: ${{ secrets.OVSX_ACCESS_TOKEN }}
        continue-on-error: true
