name: "Update version"

on:
  workflow_dispatch: 
    inputs:
      # get arguments and pass it to update_version.py
      dotextensions_version:
        description: 'dotextensions version (for 0.0.43-alpha.1, `0.0.43` is dotextensions_version)'
        required: true
        default: '0.0.44'
      alpha:
        description: 'alpha version (for 0.0.43-alpha.1 `1` is alpha version)'
        required: false
        default: '34'
      dothttp_runner_version:
        description: 'dothttp-runner version (semver like 1.0.10)'
        required: true
        default: 1.0.72
      dothttp_extensions_min_version:
        description: 'min dothttp version'
        required: false
permissions:
  id-token: write
  contents: write
env:
  python_version: 3.13
  dotextensions_version: ${{ github.event.inputs.dotextensions_version }}
  alpha: ${{ github.event.inputs.alpha }}
  dothttp_runner_version: ${{ github.event.inputs.dothttp_runner_version }}
  dothttp_extensions_min_version: ${{ github.event.inputs.dothttp_extensions_min_version }}
  storage_account_name: 'cedric05artifacts'

jobs:
  Update-version:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
      - name: Git Fetch
        run: |
          git fetch --all
      # switch to branch `VERSION`
      - name: Switch to branch
        run: git checkout VERSION
      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: ${{ env.python_version }}
      - name: Update version
        run: |
          # if latest, pass --latest otherwise --no-latest
          # if stable, pass --stable otherwise --no-stable
            if [ -z "${{ env.alpha }}" ]; then
              if [ -z "${{ env.dothttp_extensions_min_version }}" ]; then
                python update_version.py --dotextensions_version ${{ env.dotextensions_version }} --dothttp_runner_version ${{ env.dothttp_runner_version }}
              else
                python update_version.py --dotextensions_version ${{ env.dotextensions_version }} --dothttp_runner_version ${{ env.dothttp_runner_version }} --dothttp_extensions_min_version ${{ env.dothttp_extensions_min_version }}
              fi
            else
              if [ -z "${{ env.dothttp_extensions_min_version }}" ]; then
                python update_version.py --dotextensions_version ${{ env.dotextensions_version }} --alpha ${{ env.alpha }} --dothttp_runner_version ${{ env.dothttp_runner_version }}
              else
                python update_version.py --dotextensions_version ${{ env.dotextensions_version }} --alpha ${{ env.alpha }} --dothttp_runner_version ${{ env.dothttp_runner_version }} --dothttp_extensions_min_version ${{ env.dothttp_extensions_min_version }}
              fi
            fi
      - name: Commit changes
        run: |
          git config --local user.email "kesavarapu.siva@gmail.com"
          git config --local user.name "cedric05"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit. Skipping."
          else
            git add .
            git commit -m "Update version to ${{ env.dotextensions_version }}-alpha.${{ env.alpha }}, dothttp-runner version ${{ env.dothttp_runner_version }}"
            git push
          fi
      - name: Push changes
        run: git push origin VERSION
      - name: Update in Azure login storage
        uses: azure/login@v3.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Update in Azure blob storage
        uses: azure/cli@v3.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          inlineScript: |
            echo "Azure account context:"
            az account show --output json
            echo "Uploading version artifact..."
            az storage blob upload --account-name "${{ env.storage_account_name }}" --auth-mode login --container-name 'github-artifacts' --name 'dothttp-runner-version/version.json' --file version.json --overwrite
