name: "Update version"

on:
  workflow_dispatch: 
    inputs:
      # get arguments and pass it to update_version.py
      dotextensions_version:
        description: 'dotextensions version (for 0.0.43-alpha.1, `0.0.43` is dotextensions_version)'
        required: true
        default: '0.0.43'
      alpha:
        description: 'alpha version (for 0.0.43-alpha.1 `1` is alpha version)'
        required: true
      dothttp_runner_version:
        description: 'dothttp-runner version (semver like 1.0.10)'
        required: true

env:
  python_version: 3.8
  dotextensions_version: ${{ github.event.inputs.dotextensions_version }}
  alpha: ${{ github.event.inputs.alpha }}
  dothttp_runner_version: ${{ github.event.inputs.dothttp_runner_version }}

jobs:
  call-update-version:
    uses: ./.github/workflow-templates/update_version_template.yml
    with:
      dotextensions_version: ${{ env.dotextensions_version }}
      alpha: ${{ env.alpha }}
      dothttp_runner_version: ${{ env.dothttp_runner_version }}
